# -*- coding: utf-8 -*-
"""ev_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AUxoaFxNULC_vD3SUHr4tRjVthky-KU
"""

import os
import warnings
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Ignore warnings for cleaner output presentation
warnings.filterwarnings("ignore")



# Define file path
file_path = "/content/ev_charging_station_usage_grid_load.csv"
# Verify file existence dynamically
if os.path.exists(file_path):
    print(f"File found successfully: {file_path}")
else:
    print(f"Warning: Path not found. Check your directory structure.")

# Convert CSV to DataFrame
df = pd.read_csv(file_path)

print("\n--- FIRST 5 ROWS ---")
print(df.head())

print("\n--- LAST 5 ROWS ---")
print(df.tail())

print("\n--- SHAPE OF THE DATASET ---")
print(df.shape)

print("\n--- LIST OF COLUMNS ---")
print(df.columns.tolist())

print("\n--- DATA TYPES ---")
print(df.dtypes)

print("\n--- DATA FRAME INFO ---")
df.info()

print("\n--- MISSING VALUE CHECK ---")
print(df.isnull().sum())

print("\n--- DUPLICATE VALUE CHECK ---")
print(f"Duplicate records found: {df.duplicated().sum()}")

print("\n--- STATISTICAL SUMMARY ---")
print(df.describe())

# Helper function to wrap up and display each figure cleanly
def show_fig():
    plt.tight_layout()
    plt.show()


plot_no = 1

# Plot 1: Distribution of Peak Load Risk Levels
fig = plt.figure(figsize=(10, 6))
sns.countplot(
    data=df, x="peak_load_risk", order=df["peak_load_risk"].value_counts().index
)
plt.title(
    f"{plot_no}. Distribution of Peak Load Risk Levels Across All Charging Sessions"
)
show_fig()
plot_no += 1

# Plot 2: Energy Dispensed Distribution by Station Type
fig = plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x="station_type", y="energy_dispensed_kwh")
plt.title(f"{plot_no}. Energy Dispensed Distribution by Station Type")
show_fig()
plot_no += 1

# Plot 3: Relationship Between Vehicles Charged and Grid Load by Risk Level
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=df, x="vehicles_charged", y="grid_load_mw", hue="peak_load_risk"
)
plt.title(
    f"{plot_no}. Relationship Between Vehicles Charged and Grid Load by Risk Level"
)
show_fig()
plot_no += 1

# Plot 4: Distribution of Energy Dispensed per Charging Session
fig = plt.figure(figsize=(10, 6))
sns.histplot(df["energy_dispensed_kwh"], kde=True)
plt.title(f"{plot_no}. Distribution of Energy Dispensed per Charging Session")
show_fig()
plot_no += 1

# Plot 5: Vehicles Charged Variation Across City Zones
fig = plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x="city_zone", y="vehicles_charged")
plt.title(f"{plot_no}. Vehicles Charged Variation Across City Zones")
show_fig()
plot_no += 1

# Plot 6: Charging Duration Distribution by Station Type
fig = plt.figure(figsize=(10, 6))
sns.violinplot(
    data=df, x="station_type", y="avg_charging_duration_minutes"
)
plt.title(f"{plot_no}. Charging Duration Distribution by Station Type")
show_fig()
plot_no += 1

# Plot 7: Impact of Renewable Energy Usage on Grid Load
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x="renewable_energy_used_percent", y="grid_load_mw")
plt.title(f"{plot_no}. Impact of Renewable Energy Usage on Grid Load")
show_fig()
plot_no += 1

# Plot 8: Average Vehicles Charged by Station Type
fig = plt.figure(figsize=(10, 6))
sns.barplot(data=df, x="station_type", y="vehicles_charged", estimator=np.mean)
plt.title(f"{plot_no}. Average Vehicles Charged by Station Type")
show_fig()
plot_no += 1

# Plot 9: Correlation Matrix of Key Operational Metrics
fig = plt.figure(figsize=(10, 6))
numerical_cols = [
    "vehicles_charged",
    "avg_charging_duration_minutes",
    "energy_dispensed_kwh",
    "grid_load_mw",
    "renewable_energy_used_percent",
]
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap="coolwarm")
plt.title(f"{plot_no}. Correlation Matrix of Key Operational Metrics")
show_fig()
plot_no += 1

# Plot 10: Grid Load Distribution by Peak Load Risk Category
fig = plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x="peak_load_risk", y="grid_load_mw")
plt.title(f"{plot_no}. Grid Load Distribution by Peak Load Risk Category")
show_fig()
plot_no += 1

# Plot 11: Charging Duration vs Energy Dispensed by Station Type
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=df,
    x="avg_charging_duration_minutes",
    y="energy_dispensed_kwh",
    hue="station_type",
)
plt.title(f"{plot_no}. Charging Duration vs Energy Dispensed by Station Type")
show_fig()
plot_no += 1

# Plot 12: Average Renewable Energy Utilization by City Zone
fig = plt.figure(figsize=(10, 6))
sns.barplot(
    data=df, x="city_zone", y="renewable_energy_used_percent", estimator=np.mean
)
plt.title(f"{plot_no}. Average Renewable Energy Utilization by City Zone")
show_fig()
plot_no += 1

# Plot 13: Grid Load Variation by Station Type
fig = plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x="station_type", y="grid_load_mw")
plt.title(f"{plot_no}. Grid Load Variation by Station Type")
show_fig()
plot_no += 1

# Plot 14: Vehicles Charged vs Total Energy Dispensed Relationship
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x="vehicles_charged", y="energy_dispensed_kwh")
plt.title(f"{plot_no}. Vehicles Charged vs Total Energy Dispensed Relationship")
show_fig()
plot_no += 1

# Plot 15: Renewable Energy Usage Across Different Risk Levels
fig = plt.figure(figsize=(10, 6))
sns.barplot(
    data=df, x="peak_load_risk", y="renewable_energy_used_percent", estimator=np.mean
)
plt.title(f"{plot_no}. Renewable Energy Usage Across Different Risk Levels")
show_fig()
plot_no += 1

# Plot 16: Distribution of Average Charging Duration
fig = plt.figure(figsize=(10, 6))
sns.histplot(df["avg_charging_duration_minutes"], kde=True)
plt.title(f"{plot_no}. Distribution of Average Charging Duration")
show_fig()
plot_no += 1

# Plot 17: Risk Level Distribution Across Station Types
fig = plt.figure(figsize=(10, 6))
sns.countplot(data=df, x="station_type", hue="peak_load_risk")
plt.title(f"{plot_no}. Risk Level Distribution Across Station Types")
show_fig()
plot_no += 1

